name: wage_etl_dev
# docker compose -f docker-compose.dev.yml down
services:
  db:
    image: postgres:16
    container_name: dev_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 5s
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    networks:
      - wage_etl_net

  flyway:
    image: flyway/flyway:11
    container_name: dev_flyway
    depends_on:
      db:
        condition: service_healthy
    command: [
      "-url=jdbc:postgresql://db:5432/${DB_NAME}",
      "-user=${DB_USER}",
      "-password=${DB_PASSWORD}",
      "migrate"
    ]
    volumes:
      - ./sql:/flyway/sql
    networks:
      - wage_etl_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin
    networks:
      - wage_etl_net

volumes:
  db_data_dev:
  pgadmin_data_dev:

networks:
  wage_etl_net:
    driver: bridge